spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blind-box?useUnicode=true&characterEncoding=utf8
    userName: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 192.168.192.129
#    port: 6379
#    password: 123456
#    client-name: jedis
#    jedis:
#      pool:
#        max-active: 10

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:      #指定mybatis全局配置文件中的相关配置项，有了这个配置，就不需要上面的mybatis-config .xml /
#    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
